"""Is the constant-threshold family COMPLETE?

The paper builds everything on rules of the form tau = inf{t : Rhat(t) <= ell},
one parameter.  It never asks whether a cleverer predictor-adapted rule could
reach a point strictly inside that family's frontier.  If one can, the whole
geometric picture describes a sub-family rather than the achievable set, and the
"frontier" is not a frontier.

Derivation first.  At the optimum with value L, Dinkelbach says the optimal rule
minimises the LINEAR functional chi*Pr(tau>=T) + (L/Tbar)*E[(T-tau)^+].  Waiting dt
buys a waste reduction of dt, worth L/Tbar, at a failure risk h(t|F_t)dt worth chi.
So the optimal rule is

    stop when  chi * h(t | F_t)  >=  L / Tbar,

i.e. in unnormalised terms (c_f - c_p) h = g: stop when the instantaneous risk cost
rate reaches the long-run cost rate.  With trivial information this is exactly the
Barlow-Proschan condition r(t)*int_0^t Rbar - F(t) = c_p/(c_f-c_p).

So the frontier is generated by thresholding the CONDITIONAL HAZARD, not the
predicted life.  Thresholding Rhat is optimal only if Rhat is a monotone transform
of that hazard along paths.  Two things to check, and the second can refute the
paper:

  (1) the reduction to Barlow-Proschan, on a Weibull where both sides are exact;
  (2) whether enriching the rule class finds points strictly inside the constant
      threshold frontier on the real fleets.  Enrichments: a time-varying boundary
      alpha + beta*t, and a boundary using the local slope of the predictor.
"""
import sys

import numpy as np
from scipy import integrate, optimize, stats

import os.path as _p; sys.path.insert(0, _p.join(_p.dirname(_p.abspath(__file__)), "shared"))
import makefigs6 as M                                            # noqa: E402


# ---------------------------------------------------------------- part 1
def bp_reduction():
    """With trivial information the rule must reproduce Barlow-Proschan."""
    print("=" * 74)
    print("(1) trivial-information case: does the rule reduce to Barlow-Proschan?")
    print("%6s %6s %10s %12s %12s %10s" %
          ("shape", "cf/cp", "t*", "(cf-cp)r(t*)", "g(t*)", "rel.err"))
    for k in (1.5, 2.0, 2.5, 3.0, 4.0):
        for cf in (3.0, 10.0, 30.0):
            d = stats.weibull_min(k, scale=1.0)
            cp, chi = 1.0, cf - 1.0

            def g(t):
                if t <= 1e-9:
                    return np.inf
                mu = integrate.quad(d.sf, 0, t, limit=200)[0]
                return (cp + chi * d.cdf(t)) / mu

            ts = optimize.minimize_scalar(g, bounds=(1e-4, d.ppf(0.9995)),
                                          method="bounded",
                                          options={"xatol": 1e-12}).x
            r = d.pdf(ts) / d.sf(ts)                       # hazard at t*
            lhs, rhs = chi * r, g(ts)
            print("%6.1f %6.1f %10.5f %12.6f %12.6f %10.2e"
                  % (k, cf, ts, lhs, rhs, abs(lhs - rhs) / rhs))


# ---------------------------------------------------------------- part 2
def coords(paths, life, Tb, trig):
    """(omega, P_f) for a rule given by a per-unit trigger index or None."""
    waste, fail = [], []
    for i, p in enumerate(paths):
        j = trig(i, p)
        if j is None:
            waste.append(0.0)
            fail.append(1.0)
        else:
            waste.append(float(len(p) - 1 - j))     # cycles left when stopped
            fail.append(0.0)
    return float(np.mean(waste)) / Tb, float(np.mean(fail))


def lower_left_hull(P):
    """Vertices of the lower-left staircase hull of a point cloud (omega, P_f)."""
    Q = sorted(set(map(tuple, np.round(P, 12))))
    st = []
    for q in Q:                                    # ascending omega
        if st and st[-1][1] <= q[1]:               # q is dominated: drop q
            continue
        st.append(q)

    def cross(o, a, b):
        return ((a[0] - o[0]) * (b[1] - o[1])
                - (a[1] - o[1]) * (b[0] - o[0]))

    h = []
    for q in st:                                   # monotone-chain lower hull
        while len(h) >= 2 and cross(h[-2], h[-1], q) <= 0:
            h.pop()
        h.append(q)
    return np.array(h)


def inside(pt, H, tol=1e-9):
    """Is pt strictly below-left of the hull polyline H (sorted by omega)?"""
    x, y = pt
    if x < H[0][0] - tol:
        return y < H[0][1] - tol
    if x > H[-1][0] + tol:
        return y < H[-1][1] - tol
    for (x1, y1), (x2, y2) in zip(H[:-1], H[1:]):
        if x1 - tol <= x <= x2 + tol:
            t = 0.0 if x2 == x1 else (x - x1) / (x2 - x1)
            return y < y1 + t * (y2 - y1) - tol
    return False


def enrichment(name, ld):
    seq, life = ld()
    R, rm, pa, cal, val, Tb = M.prep(seq, life, seed=0)
    idx = np.concatenate([cal, val])
    paths = [np.asarray(pa[i], float) for i in idx]
    lifes = np.array([len(p) for p in paths], float)
    Tb = float(lifes.mean())

    lo = min(p.min() for p in paths)
    hi = max(p.max() for p in paths)
    ells = np.linspace(lo - .05 * Tb, hi, 160)

    # family A: the paper's constant threshold
    A = []
    for e in ells:
        def trig(i, p, e=e):
            h = np.nonzero(p <= e)[0]
            return int(h[0]) if len(h) else None
        A.append(coords(paths, lifes, Tb, trig))
    A = np.array(A)
    H = lower_left_hull(A)

    # family B: time-varying boundary alpha + beta t
    B = []
    for a in np.linspace(lo - .05 * Tb, hi, 40):
        for b in np.linspace(-0.6, 0.6, 25):
            def trig(i, p, a=a, b=b):
                thr = a + b * np.arange(len(p), dtype=float)
                h = np.nonzero(p <= thr)[0]
                return int(h[0]) if len(h) else None
            B.append(coords(paths, lifes, Tb, trig))
    B = np.array(B)

    # family C: boundary that also uses the local slope of the predictor
    C = []
    for a in np.linspace(lo - .05 * Tb, hi, 40):
        for c in np.linspace(0.0, 12.0, 25):
            def trig(i, p, a=a, c=c):
                d = np.diff(p, prepend=p[0])
                h = np.nonzero(p + c * d <= a)[0]
                return int(h[0]) if len(h) else None
            C.append(coords(paths, lifes, Tb, trig))
    C = np.array(C)

    print("=" * 74)
    print("%s  n=%d  Tbar=%.1f   family A: %d points, hull %d vertices"
          % (name, len(idx), Tb, len(A), len(H)))
    for lab, F in (("B time-varying", B), ("C slope-augmented", C)):
        vio = [p for p in F if inside(p, H)]
        if vio:
            g = max(0.0 for _ in [0])
            # depth of the deepest violation, measured in P_f
            def depth(p):
                x, y = p
                for (x1, y1), (x2, y2) in zip(H[:-1], H[1:]):
                    if x1 <= x <= x2:
                        t = 0.0 if x2 == x1 else (x - x1) / (x2 - x1)
                        return y1 + t * (y2 - y1) - y
                return 0.0
            g = max(depth(p) for p in vio)
            print("   %-18s %5d/%5d strictly inside, deepest %.5f in P_f"
                  % (lab, len(vio), len(F), g))
        else:
            print("   %-18s %5d/%5d strictly inside  <-- family A complete"
                  % (lab, 0, len(F)))


if __name__ == "__main__":
    bp_reduction()
    for nm, ld in (("FD002", M.FD002), ("FD004", M.FD004),
                   ("Severson", M.load_severson)):
        enrichment(nm, ld)
