"""The frontier from one scalar function, and whether Theorem 3's hypothesis bites.

Theorem 3 says the optimal rule thresholds the conditional hazard at level
g*/(c_f-c_p).  Combined with the tangency slope domega/dP_f = -chi/L of the
risk-waste plane and the optimality relation chi*h = L/Tbar, that forces

    domega/dP_f = -1/(Tbar * c)                                          (S)

at the frontier point generated by hazard level c.  So the frontier is parameterised
by its OWN SLOPE, the parameter being the hazard level, and omega follows from the
risk function alone by quadrature:

    omega(c) = int_c^inf P_f'(s) / (Tbar s) ds.                          (Q)

That is a sharper reduction than Theorem 4's: not a one-parameter family of laws but
a single monotone scalar function c -> P_f(c), with the waste coordinate recovered by
integration.  Both claims are exact, so an exactly solvable model tests them without
simulation noise.

Model: a Markov degradation chain on states 0..K, failure on reaching K.  From state
i the chain advances with probability p_i, fails outright with probability q_i, and
otherwise stays.  Everything needed is closed form -- the chain only moves up, so
    Pr(reach s before K | 0) = prod_{i<s} p_i/(p_i+q_i),
and mean times solve a two-term recursion backwards.

Part 2 asks whether the monotone hypothesis in Theorem 3 is doing real work or is
decorative.  With a NON-monotone hazard the one-step-look-ahead rule stops at the
first crossing, which may be a local bump; the true optimum is found by searching all
thresholds.  If the two differ, the hypothesis is necessary.
"""
import numpy as np


def chain(K, p, q):
    """Closed-form quantities for the absorbing chain."""
    # mean time from i to failure at K (no preventive stop)
    m = np.zeros(K + 1)
    for i in range(K - 1, -1, -1):
        m[i] = (1.0 + p[i] * m[i + 1]) / (p[i] + q[i])
    return m


def threshold_stats(s, K, p, q, m):
    """(P_f, omega, mean cycle length) for the rule 'replace on reaching state s'."""
    u = 1.0                                     # Pr(reach s before K), from 0
    for i in range(s):
        u *= p[i] / (p[i] + q[i])
    t = np.zeros(K + 1)                         # mean time to absorption at s or K
    for i in range(s - 1, -1, -1):
        nxt = 0.0 if i + 1 == s else t[i + 1]
        t[i] = (1.0 + p[i] * nxt) / (p[i] + q[i])
    Pf = 1.0 - u
    omega = u * m[s] / m[0]
    return Pf, omega, t[0]


def haz(i, K, p, q):
    """One-step conditional failure probability from state i."""
    return q[i] + (p[i] if i + 1 == K else 0.0)


# ------------------------------------------------------------------ part 1
def monotone_case():
    K = 60
    p = np.full(K, 0.25)
    q = 0.0015 * (1.10 ** np.arange(K))
    m = chain(K, p, q)
    Tb = m[0]

    S = np.arange(1, K)
    Pf, om, cyc = np.array([threshold_stats(int(s), K, p, q, m) for s in S]).T
    h = np.array([haz(int(s), K, p, q) for s in S])

    print("=" * 76)
    print("(1) monotone hazard: K=%d, Tbar=%.2f" % (K, Tb))

    # Lemma 1 as an independent check on the model
    chi = 9.0
    L_direct = Tb * ((1.0 + chi * Pf) / cyc) / 1.0 * (cyc / cyc)   # placeholder
    L_master = (1.0 + chi * Pf) / (1.0 - om)
    L_renew = Tb * (1.0 + chi * Pf) / cyc
    print("    Lemma 1 vs renewal-reward, max rel. gap %.2e"
          % np.max(np.abs(L_master - L_renew) / L_renew))

    # (S): chord slope against -1/(Tbar h)
    ds = np.diff(om) / np.diff(Pf)
    pred = -1.0 / (Tb * h[:-1])
    k = (Pf[:-1] > .02) & (Pf[:-1] < .85)
    print("    (S) chord slope vs -1/(Tbar h): median rel. err %.4f over %d vertices"
          % (float(np.median(np.abs(ds[k] - pred[k]) / np.abs(pred[k]))), int(k.sum())))
    print("%8s %10s %12s %12s %10s" %
          ("state", "P_f", "chord slope", "-1/(Tbar h)", "rel.err"))
    for j in range(4, 40, 6):
        print("%8d %10.5f %12.5f %12.5f %10.4f"
              % (S[j], Pf[j], ds[j], pred[j],
                 abs(ds[j] - pred[j]) / abs(pred[j])))

    # (Q): recover omega from the risk function alone
    rec = np.zeros_like(om)
    for j in range(len(S) - 2, -1, -1):
        rec[j] = rec[j + 1] + (Pf[j + 1] - Pf[j]) / (Tb * h[j])
    k2 = (Pf > .02) & (Pf < .85)
    print("    (Q) omega by quadrature from P_f alone: median rel. err %.4f"
          % float(np.median(np.abs(rec[k2] - om[k2]) / om[k2])))


# ------------------------------------------------------------------ part 2
def nonmonotone_case():
    """Is the monotone hypothesis necessary, or is it decoration?"""
    K = 60
    p = np.full(K, 0.25)
    i = np.arange(K)
    q = 0.0015 * (1.10 ** i)
    q = q + 0.11 * np.exp(-((i - 4) ** 2) / 2.0)       # a bump where the rule looks
    m = chain(K, p, q)
    Tb = m[0]
    S = np.arange(1, K)
    Pf, om, cyc = np.array([threshold_stats(int(s), K, p, q, m) for s in S]).T
    h = np.array([haz(int(s), K, p, q) for s in S])

    print("=" * 76)
    print("(2) hazard with an early bump: is one-step-look-ahead still optimal?")
    print("    hazard monotone in state: %s" % bool(np.all(np.diff(h) >= 0)))
    print("    hazard by state 1..12: " + " ".join("%.3f" % v for v in h[:12]))
    print("%8s %12s %12s %12s %10s" %
          ("chi", "OLA state", "best state", "OLA cost", "best cost"))
    for chi in (3.0, 6.0, 9.0, 15.0, 30.0):
        L = (1.0 + chi * Pf) / (1.0 - om)
        jb = int(np.argmin(L))
        gstar = L[jb] / Tb                       # optimal rate, normalised units
        cross = np.nonzero(chi * h >= gstar)[0]  # first crossing = OLA rule
        jo = int(cross[0]) if len(cross) else len(S) - 1
        flag = "" if jo == jb else "   <-- OLA suboptimal"
        print("%8.0f %12d %12d %12.5f %10.5f%s"
              % (chi, S[jo], S[jb], L[jo], L[jb], flag))


if __name__ == "__main__":
    monotone_case()
    nonmonotone_case()
